name: Android CI

on:
  push:
  pull_request:

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo The commiter is COMMITER
        env:
          COMMITER: ${{ github.event.issue.head_commit }}
